import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

//material
import {
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatGridListModule,
    MatSidenavModule,
    MatSortModule,
    MatTableModule,
    MatInputModule,
    MatSelectModule,
    MatSliderModule,
    MatRadioModule,
    MatListModule,
    MatProgressSpinnerModule,
    MatChipsModule,
    MatTooltipModule,
    MatExpansionModule,
    MatDialogModule,
    MatAutocompleteModule,
    MatTabsModule,
    MatSlideToggleModule,
    MatPaginatorModule
} from '@angular/material';

@NgModule({
  imports: [
    CommonModule,
      MatButtonModule,
      MatMenuModule,
      MatToolbarModule,
      MatIconModule,
      MatCardModule,
      MatGridListModule,
      MatSidenavModule,
      MatSortModule,
      MatTableModule,
      MatInputModule,
      MatSelectModule,
      MatSliderModule,
      MatRadioModule,
      MatListModule,
      MatProgressSpinnerModule,
      MatChipsModule,
      MatTooltipModule,
      MatExpansionModule,
      MatDialogModule,
      MatAutocompleteModule,
      MatTabsModule,
      MatSlideToggleModule,
      MatPaginatorModule
  ],
    exports: [
        MatButtonModule,
        MatMenuModule,
        MatToolbarModule,
        MatIconModule,
        MatCardModule,
        MatGridListModule,
        MatSidenavModule,
        MatSortModule,
        MatTableModule,
        MatInputModule,
        MatSelectModule,
        MatSliderModule,
        MatRadioModule,
        MatListModule,
        MatProgressSpinnerModule,
        MatChipsModule,
        MatTooltipModule,
        MatExpansionModule,
        MatDialogModule,
        MatAutocompleteModule,
        MatTabsModule,
        MatSlideToggleModule,
        MatPaginatorModule
    ],
  declarations: []
})
export class MaterialModule { }
